import { fileURLToPath } from "node:url";

/** Generated by the global setup; not committed. */
export const FIX = fileURLToPath(new URL("./.fixtures/", import.meta.url));
export const REPO = fileURLToPath(new URL("../../../", import.meta.url));

/** The production build, served by `vite preview`. */
export const BASE_URL = "http://localhost:4173";
