// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorKind } from "./ActorKind";

/**
 * Who performed an action. For the assistant, the model and provider are
 * recorded; API keys never are.
 */
export type Actor = { kind: ActorKind, name?: string | null, model?: string | null, provider?: string | null, };
