// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which program wrote an event.
 */
export type AppInfo = { name: string, version: string, 
/**
 * `cli`, `web`, `desktop`, `test`.
 */
build: string, };
