// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BandStat = { center_hz: number, 
/**
 * Mean energy in the band (dB relative to a full-scale sine).
 */
energy_db: number, 
/**
 * 10th-percentile frame energy in the band: the band's noise floor.
 */
floor_db: number, };
