// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingSource } from "./BindingSource";

/**
 * How a value relates to the clip's own analysis — the adaptive form. On
 * another clip the value is re-derived from that clip's analysis.
 */
export type Binding = { 
/**
 * `tonal_lines`, `peak_dbfs`, `quietest_region`, `clip`.
 */
feature: string, 
/**
 * Which item of a list feature, e.g. `{"near_hz": 3150, "rank": 2}`.
 */
select?: Record<string, unknown> | null, 
/**
 * `offset` (value = recorded − feature), `target` (value is the target the
 * feature is brought to), `equals`, `fraction` (of the clip's duration).
 */
relation: string, value?: number | null, source: BindingSource, note?: string, };
