// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Segment } from "./Segment";

/**
 * A spoken request, as logged (`speech.transcribed`): what was asked of the
 * recogniser, what it heard, and what the user sent. The key is never here.
 */
export type Dictation = { provider: string, model: string, 
/**
 * The host the audio was streamed to (no path, no key).
 */
host: string, 
/**
 * The stream's query parameters, in the order sent.
 */
params: Array<[string, string]>, 
/**
 * The recogniser's id for each time the microphone was opened.
 */
request_ids: Array<string>, 
/**
 * The final results, in order.
 */
segments: Array<Segment>, 
/**
 * What the user sent: the words heard, with any changes they made.
 */
words: string, 
/**
 * Seconds of audio streamed.
 */
audio_s: number, 
/**
 * From the end of listening to the last result.
 */
latency_ms: number, };
