// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One value changed (or kept) by an adaptive replay.
 */
export type DiffEntry = { step: number, op: string, param: string, recorded: unknown, new: unknown, reason: string, };
