// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One request to the model and its answer, as logged (`assistant.exchange`).
 * Everything that left the machine is here; the key never is.
 */
export type Exchange = { provider: string, model: string, 
/**
 * The host the request went to (no path, no key).
 */
host: string, 
/**
 * The request body exactly as sent (JSON text).
 */
request: string, response: unknown, latency_ms: number, 
/**
 * Why the answer could not be used, if it could not.
 */
problems?: Array<string> | null, 
/**
 * The exchange this one asked the model to correct.
 */
corrects?: string | null, };
