// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BandStat } from "./BandStat";
import type { Hum } from "./Hum";
import type { QuietRegion } from "./QuietRegion";
import type { TonalLine } from "./TonalLine";

export type Features = { version: number, t0: number, t1: number, sample_rate: number, channels: number, peak_dbfs: number, true_peak_dbfs: number, rms_dbfs: number, 
/**
 * Integrated loudness (BS.1770); absent for silence or spans under 400 ms.
 */
loudness_lufs: number | null, crest_db: number, 
/**
 * Mean per channel (linear, full scale = 1).
 */
dc_offset: Array<number>, clipped_samples: bigint, 
/**
 * 10th-percentile level of 20 ms frames, dBFS.
 */
noise_floor_dbfs: number, octave_bands: Array<BandStat>, spectral_centroid_hz: number, spectral_tilt_db_per_octave: number, tonal_lines: Array<TonalLine>, quietest_region: QuietRegion | null, hum: Hum | null, speech_activity_ratio: number, bandwidth_hz: number, bandwidth_limited: boolean, };
