// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Hum = { 
/**
 * 50 or 60.
 */
fundamental_hz: number, 
/**
 * Harmonics 1–6 found as lines.
 */
harmonics_found: number, strength_db: number, };
