// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A label as it stands now.
 */
export type Label = { id: string, 
/**
 * The stretch it marks, in seconds of the original; `t0 < t1`.
 */
t0: number, t1: number, 
/**
 * The frequency band (Hz) of a time × frequency area; both or neither.
 */
f_lo?: number | null, f_hi?: number | null, 
/**
 * One line, as the user last wrote it.
 */
text: string, 
/**
 * Where it was added in the log, and when.
 */
seq: number, ts: string, };
