// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Lineage = { parent_project: string, parent_name: string, 
/**
 * Hash of the parent's `project.clone_made` event; the clone's log starts from it.
 */
parent_head: string, forked_at_step?: string | null, forked_at_event?: string | null, 
/**
 * Ancestor project ids, parent first.
 */
ancestors: Array<string>, };
