// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";
import type { Via } from "./Via";

/**
 * One request and its answer, as the log records them.
 */
export type LoggedRequest = { 
/**
 * Where it starts in the log: its dictation, its first exchange with the
 * model, or the event that put its steps on the stack.
 */
seq: number, ts: string, 
/**
 * The words sent; empty for steps that came without any.
 */
words: string, via: Via, 
/**
 * Through what its steps arrived; absent when it put none on the stack.
 */
origin?: Origin | null, 
/**
 * The model asked, and its provider.
 */
model?: string | null, provider?: string | null, 
/**
 * The words were dictated.
 */
spoken: boolean, 
/**
 * The answer in words: the model's, or what the router understood.
 */
text?: string | null, 
/**
 * Why the model's last answer could not be used.
 */
problems?: Array<string> | null, 
/**
 * The recipe replayed, by name.
 */
recipe?: string | null, 
/**
 * Operations the model's last answer proposed (none for a local request).
 */
proposed: number, 
/**
 * The steps it put on the stack, in stack order; empty when it put none.
 */
step_ids: Array<string>, 
/**
 * Names it: its first step, or else its last exchange with the model.
 */
key: string, };
