// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lineage } from "./Lineage";
import type { LogHead } from "./LogHead";
import type { ProjectInfo } from "./ProjectInfo";
import type { SourceInfo } from "./SourceInfo";
import type { SourceRef } from "./SourceRef";
import type { StackSummary } from "./StackSummary";

export type Manifest = { format: string, format_version: number, project: ProjectInfo, source: SourceRef, source_info: SourceInfo, lineage?: Lineage | null, 
/**
 * Interface state (zoom, scroll, selection, colour range). Not evidence.
 */
view: Record<string, unknown>, log: LogHead, stack: StackSummary, 
/**
 * Parameters of the final limiter (defaults if empty).
 */
final_limiter: Record<string, unknown>, };
