// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineageCheck } from "./LineageCheck";
import type { Verification } from "./Verification";

/**
 * What opening a project found. Problems are reported, never silently repaired.
 */
export type OpenReport = { source_sha256: string, source_ok: boolean, log: Verification, lineage: Array<LineageCheck>, projection_ok: boolean, manifest_consistent: boolean, problems: Array<string>, };
