// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Through what a step arrived.
 */
export type Origin = "console" | "panel" | "cli" | "recipe" | "automation" | "api";
