// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParamSpec = { id: string, title: string, help: string, required: boolean, default: unknown, } & ({ "type": "number", unit?: string | null, min: number, max: number, step?: number | null, auto_allowed: boolean, } | { "type": "integer", min: bigint, max: bigint, auto_allowed: boolean, } | { "type": "enum", values: Array<string>, } | { "type": "bool" } | { "type": "time_range" } | { "type": "lines", max_items: number, });
