// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposedStep } from "./ProposedStep";

/**
 * What the model answered.
 */
export type Proposal = { 
/**
 * Empty when the model answered in words only (a question, say).
 */
steps: Array<ProposedStep>, 
/**
 * The model's words: its explanation, or its question.
 */
text: string | null, 
/**
 * Several operations to be accepted together.
 */
plan: boolean, 
/**
 * Operations the model asked to see (`describe_operations`) before
 * choosing. When there are any, nothing else in the answer is acted on:
 * the operations are described and the model asked again.
 */
describe?: Array<string>, };
