// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * One operation the model proposed, validated.
 */
export type ProposedStep = { op: string, op_version: number, 
/**
 * Every parameter written out, as validated.
 */
params: Record<string, unknown>, scope: Scope, };
