// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuietRegion = { t0: number, t1: number, 
/**
 * Mean level over the region, dBFS (RMS).
 */
level_dbfs: number, 
/**
 * Whether the two halves agreed within 1 dB.
 */
stable: boolean, 
/**
 * Median absolute per-bin difference between the halves, dB.
 */
halves_diff_db: number, };
