// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Rating = { 
/**
 * `step`, `plan` or `stack`.
 */
target_kind: string, 
/**
 * Step id, plan id, or stack hash.
 */
target: string, 
/**
 * 1–5.
 */
overall: number, dims: { [key in string]: number }, note?: string | null, };
