// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeOrigin } from "./RecipeOrigin";
import type { RecipeStep } from "./RecipeStep";

export type Recipe = { format: string, format_version: number, name: string, title?: string | null, description: string, created_from?: RecipeOrigin | null, features_version: number, steps: Array<RecipeStep>, };
