// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeOrigin = { project: string, source_sha256: string, stack_hash: string, steps: Array<string>, };
