// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Binding } from "./Binding";
import type { Scope } from "./Scope";

export type RecipeStep = { op: string, op_version: number, params: Record<string, unknown>, 
/**
 * The exact form as recorded (absent in built-in recipes).
 */
resolved?: Record<string, unknown> | null, scope: Scope, bindings: { [key in string]: Binding }, optional: boolean, enabled: boolean, title?: string | null, intent?: string | null, rationale?: string | null, };
