// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffEntry } from "./DiffEntry";
import type { ReplayMode } from "./ReplayMode";
import type { StepDraft } from "./StepDraft";

/**
 * Drafts ready to preview as a plan, and the dry-run diff.
 */
export type ReplayPlan = { recipe: string, recipe_hash: string, mode: ReplayMode, drafts: Array<StepDraft>, 
/**
 * Recipe step index for each draft.
 */
step_indices: Array<number>, diff: Array<DiffEntry>, 
/**
 * Recipe steps not included (switched off or optional).
 */
skipped: Array<number>, };
