// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rounds already taken for one request.
 */
export type Rounds = { 
/**
 * The model has been shown operations it asked to see.
 */
described: boolean, 
/**
 * The model has been asked to correct an answer.
 */
corrected: boolean, };
