// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

export type RoutedStep = { op: string, params: Record<string, unknown>, scope: Scope, 
/**
 * What was understood, in words (shown, and recorded as the rationale).
 */
understood: string, };
