// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutedStep } from "./RoutedStep";

/**
 * How a request is handled.
 */
export type Route = { "route": "recipe", name: string, } | { "route": "steps", steps: Array<RoutedStep>, } | { "route": "listen", which: string, } | { "route": "undo" } | { "route": "redo" } | { "route": "model" };
