// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Scope = { "kind": "clip" } | { "kind": "time_range", t0: number, t1: number, } | { "kind": "band", f_lo: number, f_hi: number, } | { "kind": "tf_patch", t0: number, t1: number, f_lo: number, f_hi: number, };
