// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One final result from the recogniser.
 */
export type Segment = { text: string, confidence: number, };
