// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the interface has selected, if anything.
 */
export type Selection = { 
/**
 * A time range: `[t0, t1]` in seconds.
 */
time?: [number, number] | null, 
/**
 * A time × frequency area: `[t0, t1, f_lo, f_hi]` (seconds, hertz).
 */
area?: [number, number, number, number] | null, };
