// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceInfo = { 
/**
 * Container format as the decoder names it, e.g. `wave`, `mp3`, `flac`.
 */
container: string, 
/**
 * Codec short name, e.g. `pcm_s16le`, `mp3`.
 */
codec: string, sample_rate: number, channels: number, frames: bigint, duration_s: number, bits_per_sample: number | null, decoder: string, };
