// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceRef = { sha256: string, filename: string, size: bigint, path: string, };
