// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FreqScale } from "./FreqScale";

export type SpectrogramRequest = { t0: number, t1: number, columns: number, rows: number, f_min: number, f_max: number, scale: FreqScale, db_min: number, db_max: number, 
/**
 * FFT size at 48 kHz (scaled with the sample rate). Typically 2048.
 */
fft_at_48k: number, };
