// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewRecord } from "./PreviewRecord";
import type { StackChange } from "./StackChange";
import type { StackEntry } from "./StackEntry";
import type { Step } from "./Step";

export type StackState = { 
/**
 * The active steps, in order: what renders.
 */
steps: Array<Step>, 
/**
 * Hash of the event that put each active step's current version on the
 * stack (for a step inherited by a clone, the event in its parent's log).
 */
step_events: Array<string>, 
/**
 * Every step that has been on the stack, in stack order, active or excluded.
 */
entries: Array<StackEntry>, 
/**
 * The current versions of the excluded steps.
 */
excluded: { [key in string]: Step }, stack_hash: string, previews: { [key in string]: PreviewRecord }, 
/**
 * preview id → `accepted` or `rejected`.
 */
decided: { [key in string]: string }, ratings: Array<Record<string, unknown>>, annotations: Array<Record<string, unknown>>, 
/**
 * Changes Undo can take back, the last one last.
 */
undo: Array<StackChange>, 
/**
 * Changes Undo took back that Redo can repeat, the last one last.
 */
redo: Array<StackChange>, };
