// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One place in the stack.
 */
export type StackEntry = { step_id: string, 
/**
 * Plays its part in the render. An excluded step keeps its place and can
 * be restored to it.
 */
active: boolean, 
/**
 * Edits in effect (measuring it again included; an undone edit is not counted).
 */
edits: number, 
/**
 * Its values were measured on audio that is no longer its input
 * (`Step::resolved_on`).
 */
drifted: boolean, 
/**
 * Why it was removed, if it is excluded and a reason was given.
 */
reason?: string | null, };
