// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewRecord } from "./PreviewRecord";
import type { Step } from "./Step";

export type StackState = { steps: Array<Step>, 
/**
 * Hash of the event that put each step on the stack.
 */
step_events: Array<string>, stack_hash: string, previews: { [key in string]: PreviewRecord }, 
/**
 * preview id → `accepted` or `rejected`.
 */
decided: { [key in string]: string }, ratings: Array<Record<string, unknown>>, annotations: Array<Record<string, unknown>>, };
