// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change to the stack that Undo can take back and Redo repeat.
 */
export type StackChange = { 
/**
 * The event that made the change.
 */
event: string, 
/**
 * `applied` (accepted steps too), `excluded`, `restored` or `edited`.
 */
kind: string, step_ids: Array<string>, 
/**
 * For an edit: the event in this log that holds the version before it.
 */
before?: string | null, };
