// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Features } from "./Features";

/**
 * Features of a step's input or output: the whole clip, and the step's time
 * scope when it has one.
 */
export type StateSnapshot = { clip: Features, scope?: Features | null, };
