// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Actor } from "./Actor";
import type { Binding } from "./Binding";
import type { Origin } from "./Origin";
import type { Scope } from "./Scope";

/**
 * A step as proposed, before it is resolved on the clip.
 */
export type StepDraft = { op: string, op_version?: number | null, params: Record<string, unknown>, scope: Scope, actor: Actor, origin: Origin, intent?: string | null, rationale?: string | null, note?: string | null, 
/**
 * Declared bindings (the assistant's or a recipe's).
 */
bindings: { [key in string]: Binding }, 
/**
 * Exact replay: use these resolved values instead of resolving on this clip.
 */
resolved?: Record<string, unknown> | null, };
