// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Actor } from "./Actor";
import type { Binding } from "./Binding";
import type { InheritedRef } from "./InheritedRef";
import type { OpClass } from "./OpClass";
import type { Origin } from "./Origin";
import type { Scope } from "./Scope";
import type { StateSnapshot } from "./StateSnapshot";

export type Step = { step_id: string, plan_id?: string | null, op: string, op_version: number, 
/**
 * Parameters as given, every one written out; may contain `auto`.
 */
params: Record<string, unknown>, 
/**
 * The concrete values used on this clip — the exact form.
 */
resolved: Record<string, unknown>, scope: Scope, 
/**
 * The adaptive form, keyed by parameter (`f_lo`, `scope.t0`, …).
 */
bindings: { [key in string]: Binding }, actor: Actor, origin: Origin, intent?: string | null, rationale?: string | null, note?: string | null, class: OpClass, label: string, state_before?: StateSnapshot | null, state_after?: StateSnapshot | null, 
/**
 * What the DSP measured: over the preview window in a preview, over the
 * whole clip once accepted.
 */
measurements: Record<string, unknown>, input_hash: string, output_hash?: string | null, stack_hash?: string | null, inherited_from?: InheritedRef | null, };
