// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TonalLine = { freq_hz: number, 
/**
 * Width at half the prominence (in dB) above the neighbourhood.
 */
width_hz: number, 
/**
 * Level above the median of the surrounding material, dB.
 */
prominence_db: number, 
/**
 * Share of ~1 s segments (0–1) in which the line stands out by ≥ 3 dB.
 */
persistence: number, 
/**
 * Long-term level at the line (dB relative to a full-scale sine).
 */
level_db: number, 
/**
 * Prominence in the speech pauses alone; absent when the span has less
 * than `MIN_PAUSE_S` of pause.
 */
pause_prominence_db?: number | null, };
