// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the model is shown an operation: always with its full schema
 * (`core`), or in a one-line index, the schema sent when it asks
 * (`on_demand`). Keeps requests small as the catalogue grows.
 */
export type ToolTier = "core" | "on_demand";
