// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One earlier turn of the conversation, as words.
 */
export type Turn = { 
/**
 * `user` or `assistant`.
 */
role: string, text: string, };
