// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerifyFailure } from "./VerifyFailure";

export type Verification = { ok: boolean, 
/**
 * Number of events that verified before the first failure (or all of them).
 */
verified: bigint, first_failure: VerifyFailure | null, 
/**
 * Hash of the last verified event.
 */
head: string, };
